# Generated by Django 5.0.7 on 2024-07-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_names', models.CharField(max_length=255, verbose_name='Please State Your Official Names')),
                ('country', models.CharField(max_length=100, verbose_name='Please select your Country')),
                ('assessor_name', models.CharField(max_length=255, verbose_name='Name Of Assessor that Audited the Call')),
                ('assessor_email', models.EmailField(max_length=254, verbose_name='Quality Assessor Email address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Appealed call phone number')),
                ('agent_listened', models.BooleanField(verbose_name='Did Agent Listen to the Call again?')),
                ('parameter_not_fairly_scored', models.CharField(max_length=255, verbose_name='Parameter that was supposedly not fairly scored')),
                ('feedback_received', models.TextField(verbose_name='Feedback Received')),
                ('reason_for_appeal', models.TextField(verbose_name='Please state your reason for appeal')),
                ('call_link', models.URLField(verbose_name='Attach the link to the call that was audited')),
            ],
        ),
    ]
