# Generated by Django 5.0.7 on 2024-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal_form',
            name='agent_listened',
            field=models.CharField(max_length=5, verbose_name='Did Agent Listen to the Call again?'),
        ),
    ]
